Repository vallot/CATTools, pull requests merged in 2018-10, with the labels that each got.

#736 Parton Shower Weights and their information
  CatProducer/plugins/GenWeightsProducer.cc
Labels: production

#737 Fix crashing during
  DataFormats/src/GenTop.cc
Labels: bug

#738 gen weight bug fix
  CatProducer/plugins/GenWeightsProducer.cc
Labels: bug

#739 PSWeight minor fix
  DataFormats/interface/GenWeights.h
  DataFormats/src/GenWeights.cc
Labels: bug, dataformat
